#!/bin/sh
# Requires Docker and curl. Runs on the Mac and in GitHub Actions.
set -eu

image=${1:-portfolio:local}
container="portfolio-smoke-$$"
test_dir=$(mktemp -d)

cleanup() {
    docker rm -f "$container" >/dev/null 2>&1 || true
    rm -rf "$test_dir"
}
trap cleanup EXIT
trap 'exit 1' HUP INT TERM

docker run --rm -d --name "$container" -p 127.0.0.1::80 "$image" >/dev/null
port=$(docker port "$container" 80/tcp | sed 's/.*://')
url="http://127.0.0.1:$port"

ready=false
for attempt in $(seq 1 30); do
    if curl -fsS "$url/portfolio/" -o "$test_dir/index.html" 2>/dev/null; then
        ready=true
        break
    fi
    sleep 1
done
if [ "$ready" != true ]; then
    docker logs "$container"
    echo 'The portfolio did not start.' >&2
    exit 1
fi

grep -q '<base href="/portfolio/">' "$test_dir/index.html"
grep -q 'Rahul Origanti | Portfolio' "$test_dir/index.html"

for path in / /portfolio; do
    status=$(curl -sS -D "$test_dir/headers" -o /dev/null -w '%{http_code}' "$url$path")
    [ "$status" = 301 ]
    tr -d '\r' < "$test_dir/headers" | grep -Ei '^location: .*/portfolio/$' >/dev/null
done

# Client-side routes must serve the app shell too.
curl -fsS "$url/portfolio/example-route" -o "$test_dir/route.html"
cmp "$test_dir/index.html" "$test_dir/route.html"

# Follow the actual URLs generated by Angular, including the favicon. A 200
# alone is insufficient: a misrouted asset can return the HTML app shell.
grep -oE '(src|href)="[^"]+\.(js|css|svg)(\?[^"]*)?"' "$test_dir/index.html" \
    | cut -d '"' -f 2 | sort -u > "$test_dir/assets"
grep -q '\.js' "$test_dir/assets"
grep -q '\.css' "$test_dir/assets"
grep -q 'favicon.svg' "$test_dir/assets"
while IFS= read -r asset; do
    case "$asset" in
        /*|*://*) echo "Asset escapes /portfolio/: $asset" >&2; exit 1 ;;
    esac
    curl -fsS -D "$test_dir/headers" "$url/portfolio/$asset" -o "$test_dir/asset"
    test -s "$test_dir/asset"
    case "$asset" in
        *.js*) content_type='(application|text)/javascript' ;;
        *.css*) content_type='text/css' ;;
        *.svg*) content_type='image/svg\+xml' ;;
    esac
    grep -Ei "^content-type: $content_type" "$test_dir/headers" >/dev/null
    echo "Asset OK: $asset"
done < "$test_dir/assets"

docker exec "$container" nginx -t
docker exec "$container" wget -q -O /dev/null http://127.0.0.1/portfolio/
echo 'Image OK: page, redirects, client routes, assets and health probe.'
